apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: pulumi-llmops
  namespace: argocd
spec:
  project: default
  source:
    repoURL: https://github.com/CuteDandelion/pulumi-policy-as-code.git
    targetRevision: main
    path: argocd-app
  destination:
    server: https://kubernetes.default.svc
    namespace: default
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true
